### ISSUE TITLE
你好，https://github.com/electron/electron/issues/9173

### ISSUE THREAD

**Issue by aceimnorstuvwxz** [zjfjiayou/react-native-mind#3]
https://github.com/electron/electron/issues/9173
我看到您也遇到这个问题，我打扰问下你有后续进展吗

**Comment by zjfjiayou** [comment]
这个问题没有好的解决办法，最后尝试使用不同版本的electron，其中有的版本是没有这个问题的，你可以尝试一下1.6.17或者1.8.x的版本

**Comment by aceimnorstuvwxz** [comment]
感谢回复！
